import os
from dotenv import load_dotenv
from openai import OpenAI

#Load Environment Variables
load_dotenv()

#Initialize OpenAI Client
client = OpenAI(
    api_key=os.getenv('OPENAI_API_KEY')
)

#System Promp
SYSTEM_PROMPT = """
You are an AI shopping assistant for an e-commerce platform.

Your job is to help users choose from the products retrieved by the search system.

Rules:
1. Recommend ONLY from the provided products.
2. Never invent products or product details.
3. Consider the user's query carefully, including:
   - product type
   - price preferences
   - brand preferences
   - intended use
4. Explain briefly why the recommended products match the user's needs.
5. Highlight important differences between products when relevant.
6. Use a professional, helpful, and concise tone.
7. Keep the response under 120 words.
8. If only one product is retrieved, explain why it is a strong match.
9. If no products are retrieved, politely state that no matching products were found.
"""

def generate_recommendation(query: str, products: list) -> str:
    """
     Generate an AI recommendation summary based on retrieved products.

    Parameters
    ----------
    query : str
        Original user query.

    products : list
        List of retrieved product dictionaries.

    Returns
    -------
    str
        Recommendation summary generated by the LLM.
    """

    #Handle empty results
    if not products:
        return (
            "I couldn't find products matching your requirements. "
            "Try adjusting the price range, brand, or search terms."
        )

    #Buil Product Context
    product_context=""

    for idx, product in enumerate(products, start=1):
        product_context+=(
            f'Product {idx}:\n'
            f'Name: {product.get('name', 'Unknown')}\n'
            f'Brand: {product.get('brand', 'Unknown')}\n'
            f'Category: {product.get('category', 'Unknown')}\n'
            f'Subcategory: {product.get('subcategory', 'Unknown')}\n'
            f'Price: ₹{product.get('price', 'N/A')}\n\n'

        )

    user_prompt = f"""
User Query:
{query}

Retrieved Products:
{product_context}

Provide a concise recommendation summary based ONLY on the retrieved products.
Mention the strongest matches and explain why they suit the user's query.
"""

    try:
        response = client.responses.create(
            model='gpt-5-mini',
            instructions=SYSTEM_PROMPT,
            input=user_prompt
        )

        return response.output_text.strip()
    
    except Exception as e:
        print(f'LLM Error: {e}')

        return (
            "Recommendations are currently unavailable, "
            "but the search results above are still relevant "
            "to your query."        
        )